### PR TITLE
Fixed using the LIBRT variable 

### PR DESCRIPTION
**Pull request by jbangelo**

### CODE REVIEW

**Review by mfine — COMMENTED** [review]
Looks ok to me

**Review by woodfell — APPROVED** [review]
Look ok.

Wondering why this came up though, I asked Chandra to test this work on his mac before merging and it worked fine then. Strange.

**Comment by jbangelo** [comment]
Digging into this a bit more it looks like it's an unfortunate interaction between the CMake in libcheck and the CMake in Google benchmark. benchmark is using the `LIBRT` variable to contain the search result when looking for librt. So when we pull in both repos one messes with the other.

@woodfell With that in mind do you think it would be better to make a change in our `FindBenchmark.cmake` module to try and unset this variable?

**Comment by woodfell** [comment]
@jbangelo That sounds pretty nasty. It's because of the call to `find_library` that sets a `CACHE` variable, right? Normally variables should not be able to leak from one submodule to another given how they are only propagated downwards.

It's unfortunate, maybe unsetting it like you say would be the best option. Alternatively changing the order in which those projects are included may also fix it, but that is rather prone to breaking again in the future.

**Comment by jbangelo** [comment]
Closing this in favor of the alternate approach discussed. Will open another PR in the cmake repo shortly.

**Comment by jbangelo** [comment]
Merging this anyways, per our discussion.

**Pull request merged**
